const TIPO_VALOR = {
    ENTERO: 'VAL_ENTERO',
    DOBLE: 'VAL_DOBLE',
    CADENA: 'VAL_CADENA',
    CARACTER: 'VAL_CARACTER',
    BOOLEAN: 'VAL_BOOLEAN',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    NULL: 'VAL_NULL'
}