const TIPO_VALOR = {
    ENTERO: 'VAL_ENTERO',
    DOUBLE: 'VAL_DOUBLE',
    CADENA: 'VAL_CADENA',
    CARACTER: 'VAL_CARACTER',
    BOOLEAN: 'VAL_BOOLEAN',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    NULL: 'VAL_NULL'
}